### ISSUE TITLE
It gives an error on nested url

### ISSUE THREAD

**Issue by davran-siv** [rokoroku/react-mobx-typescript-boilerplate#19]
If I create an URL /foo/bar it gives an error Uncaught SyntaxError: Unexpected token '<'
`<Route path="/foo/bar" component={TodoApp} />`
What am I doing wrong?

**Comment by davran-siv** [comment]
This webpack config is fixing the error
`publicPath: '/',` 
here 
`  
output: {
    path: outPath,
    publicPath: '/',
    filename: isProduction ? '[contenthash].js' : '[hash].js',
    chunkFilename: isProduction ? '[name].[contenthash].js' : '[name].[hash].js'
  },
`
https://stackoverflow.com/questions/35584327/webpack-loads-from-the-wrong-url-when-the-path-changes

**Comment by Emixam23** [comment]
Thanks for adding the link, I didn't get your solution at first :) Thanks again !
