### ISSUE TITLE
Does not produce the 'styles.css' file.

### ISSUE THREAD

**Issue by delaneyj** [rokoroku/react-mobx-typescript-boilerplate#2]
It appears the boilerplate is using ExtractTextPlugin but when you use `npm run build` the output of `styles.css` is not in the `dist` folder.  Also its not picked up by the Html plugin.  Trying to include extra .css files via import and not seeing them.  Is there something I'm missing?

**Comment by rokoroku** [comment]
I couldn't reproduce this issue. With clean npm install & build, `styles.css` file is successfully generated and injected in `index.html` 

Could you please give me more information such as modified files or your build environment?

**Comment by delaneyj** [comment]
Looks like I was looking in the wrong directory (multiple copies of the boilerplate) for the dist issue.  Having other issues with css not getting loaded but orthogonal to your boilerplate.  Thanks!
